### ISSUE TITLE
visibleCount

### ISSUE THREAD

**Issue by zichen27** [jayZOU/vue-big-tree#2]
visibleCount() {
      return Math.floor(this.option.height / this.option.itemHeight) * 3;
 }
这里为什么要 * 3 ?

**Comment by jayZOU** [comment]
是个bug
原本是打算缓存前后部分数据，避免快速滚动出现空白，这里应该要在计算可视区域里面来处理才对
https://github.com/jayZOU/vue-big-tree/blob/master/src/components/vueBigTree.vue#L206
